[pytest]
python_files = *test*.py
python_classes = *Test*
python_functions = *test*
testpath = tests test_API
# Маркеры для разделения тестов
markers =
    ui: UI-тесты (Selenium)
    api: API-тесты (Requests)